This script shows how to format data from kobotoolbox to Arches: work in progress

Timeline for writing the script

* Saturday: writing of the script (beginning)
* Monday: writing of the script (end)

In [1]:
# concepts_dict
concept_dict_name = "Institutes.xlsx"

In [2]:
import pandas as pd

import xlrd

import openpyxl #required for xlrd 2.0.1 and higher

parent = pd.read_excel('odk_data.xlsm') 
# df.to_csv('your_new_name.csv')

concept_df = pd.read_excel(concept_dict_name)


# Read the excel spreadsheet from the server (): 
# Doing join (parent to children) 
# make blank repeated instances
#  (create dictinary)
# Rename columns
# Export only columns that exist in arches

In [3]:
transects =  pd.read_excel('odk_data.xlsm', sheet_name = 'transects')

transects

,transects/transect_direction,transects/transect_direction_info/transect_direction_other,transects/transect_direction_info/transect_id,transects/transects_group/repeat_count,transects/transects_group/unit_count,_id,_uuid,_submission_time,_index,_parent_table_name,_parent_index,_tags,_notes
0,CP,NaN,33,1,1,NaN,NaN,NaN,1,acg2C7sESTJzjLNtwRpVKW,1,NaN,NaN
1,NS,NaN,1,2,2,NaN,NaN,NaN,2,acg2C7sESTJzjLNtwRpVKW,7,NaN,NaN
2,NS,NaN,2,1,1,NaN,NaN,NaN,3,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
3,NS,NaN,1,1,1,NaN,NaN,NaN,4,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
4,other,F,3,1,1,NaN,NaN,NaN,5,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
5,CP,NaN,1,1,1,NaN,NaN,NaN,6,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
6,CP,NaN,1,1,1,NaN,NaN,NaN,7,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
7,EW,NaN,1,1,1,NaN,NaN,NaN,8,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
8,other,NS,1,1,1,NaN,NaN,NaN,9,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN
9,CP,NaN,1,1,1,NaN,NaN,NaN,10,acg2C7sESTJzjLNtwRpVKW,8,NaN,NaN

In [4]:
#Join the two tables (left join)
merge = parent.merge(transects, how= 'left', left_on=['_index'], right_on = ['_parent_index'])

In [5]:
merge

,start,end,today,institute_name,recorder_name,existing_reference,site_source,new_site_id,pre_site_id,pre_grid_id,...,transects/transects_group/repeat_count,transects/transects_group/unit_count,_id_y,_uuid_y,_submission_time_y,_index_y,_parent_table_name_y,_parent_index_y,_tags_y,_notes_y
0,2022-03-24 21:34:36.670,2022-03-24 22:01:57.497,44644,university_of_cambridge,CAM09,NaN,newly_recorded_site/built_heritage,52445.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,1.0,acg2C7sESTJzjLNtwRpVKW,1.0,NaN,NaN
1,2022-03-24 22:46:30.747,2022-03-24 22:47:38.857,44644,shah_abdul_latif_university,SALU01,NaN,newly_recorded_site/built_heritage,552.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-03-25 00:17:50.137,2022-03-25 00:18:27.377,44645,university_of_cambridge,CAM01,NaN,newly_recorded_site/built_heritage,36.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-03-25 00:34:46.250,2022-03-25 00:35:19.627,44645,upf,UPF02,NaN,newly_recorded_site/built_heritage,255.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-03-25 00:36:28.543,2022-03-25 00:37:11.257,44645,university_of_punjab,PU02,NaN,newly_recorded_site/built_heritage,255.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2022-03-28 03:47:36.133,2022-03-28 03:59:49.700,44648,university_of_cambridge,CAM09,-26.172543 27.9928573 1710.563 8.559;-26.17255...,preloaded_site,NaN,8754568.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2022-03-28 03:59:56.340,2022-03-28 04:09:46.650,44648,shah_abdul_latif_university,SALU01,NaN,preloaded_site,NaN,25485.0,NaN,...,2.0,2.0,NaN,NaN,NaN,2.0,acg2C7sESTJzjLNtwRpVKW,7.0,NaN,NaN
7,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,3.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
8,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,4.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
9,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,5.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
10,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,6.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
11,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,7.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
12,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,8.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
13,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,9.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
14,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,upf,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,10.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
15,2022-03-29 16:28:00.197,2022-03-30 12:16:09.827,44649,university_of_cambridge,CAM01,NaN,newly_recorded_site/built_heritage,3558.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# create concept dict
concept_dict = pd.Series(concept_df.institute.values,index=concept_df.institute_coor).to_dict()

In [7]:
# replace values using dict
merge['institute_name'] = merge['institute_name'].map(concept_dict).fillna(merge['institute_name'])

In [8]:
merge

,start,end,today,institute_name,recorder_name,existing_reference,site_source,new_site_id,pre_site_id,pre_grid_id,...,transects/transects_group/repeat_count,transects/transects_group/unit_count,_id_y,_uuid_y,_submission_time_y,_index_y,_parent_table_name_y,_parent_index_y,_tags_y,_notes_y
0,2022-03-24 21:34:36.670,2022-03-24 22:01:57.497,44644,University of Cambridge,CAM09,NaN,newly_recorded_site/built_heritage,52445.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,1.0,acg2C7sESTJzjLNtwRpVKW,1.0,NaN,NaN
1,2022-03-24 22:46:30.747,2022-03-24 22:47:38.857,44644,Shah Abdul-latif University,SALU01,NaN,newly_recorded_site/built_heritage,552.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-03-25 00:17:50.137,2022-03-25 00:18:27.377,44645,University of Cambridge,CAM01,NaN,newly_recorded_site/built_heritage,36.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-03-25 00:34:46.250,2022-03-25 00:35:19.627,44645,UPF,UPF02,NaN,newly_recorded_site/built_heritage,255.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-03-25 00:36:28.543,2022-03-25 00:37:11.257,44645,University of Punjab,PU02,NaN,newly_recorded_site/built_heritage,255.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2022-03-28 03:47:36.133,2022-03-28 03:59:49.700,44648,University of Cambridge,CAM09,-26.172543 27.9928573 1710.563 8.559;-26.17255...,preloaded_site,NaN,8754568.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2022-03-28 03:59:56.340,2022-03-28 04:09:46.650,44648,Shah Abdul-latif University,SALU01,NaN,preloaded_site,NaN,25485.0,NaN,...,2.0,2.0,NaN,NaN,NaN,2.0,acg2C7sESTJzjLNtwRpVKW,7.0,NaN,NaN
7,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,3.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
8,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,4.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
9,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,5.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
10,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,6.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
11,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,7.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
12,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,8.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
13,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,9.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
14,2022-03-28 04:10:09.200,2022-03-28 04:24:57.313,44648,UPF,UPF01,NaN,newly_recorded_site/built_heritage,5524899.0,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,10.0,acg2C7sESTJzjLNtwRpVKW,8.0,NaN,NaN
15,2022-03-29 16:28:00.197,2022-03-30 12:16:09.827,44649,University of Cambridge,CAM01,NaN,newly_recorded_site/built_heritage,3558.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN